//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI656_Alquiler_Equipos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RentalDetail
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Sub Total")]
        public decimal SubTotal { get; set; }
        [Required]
        [Display(Name = "Equipo")]
        public int EquipmentId { get; set; }
        [Required]
        [Display(Name = "Alquiler")]
        public int RentalId { get; set; }
        [Required]
        [Display(Name = "Dia Inicio")]
        public System.DateTime StartDate { get; set; }
        [Required]
        [Display(Name = "Dia Expiracion")]
        public System.DateTime ExpirationDate { get; set; }
        [Required]
        [Display(Name = "Cantidad")]
        public int Quantity { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Rental Rental { get; set; }
    }
}
