//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI656_AlquilerEquipos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquiler_detalle
    {
        public int id { get; set; }
        public decimal precio { get; set; }
        public int equipo_id { get; set; }
        public int alquiler_id { get; set; }
    
        public virtual alquiler alquiler { get; set; }
        public virtual equipo equipo { get; set; }
    }
}
