//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI656_AlquilerEquipos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alquiler()
        {
            this.alquiler_detalle = new HashSet<alquiler_detalle>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal total { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public int cliente_id { get; set; }
        public int usuario_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquiler_detalle> alquiler_detalle { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
