//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI656_AlquilerEquipos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_AlquilerEquipoEntities : DbContext
    {
        public db_AlquilerEquipoEntities()
            : base("name=db_AlquilerEquipoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alquiler> alquiler { get; set; }
        public virtual DbSet<alquiler_detalle> alquiler_detalle { get; set; }
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<equipo> equipo { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<tipo_documento> tipo_documento { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
