//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI656_AlquilerEquipos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public int EquipmentStateId { get; set; }
        public int Stock { get; set; }
        public int EquipmentTypeId { get; set; }
        public decimal PriceByHour { get; set; }
        public decimal PriceByDay { get; set; }
        public decimal PriceByWeek { get; set; }
        public decimal ExtraHour { get; set; }
        public decimal ExtraDay { get; set; }
        public string ImagePath { get; set; }
    
        public virtual EquipmentState EquipmentState { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
    }
}
